server_port = 4446
default_lang = "fr"
static_files_route = "/static"
page_config = "./pages.toml"
notification_template = "notification.html"




# Additionnal context
[plain_context.site]
name = "Litchi Pi"
author_name = "Litchi Pi"
author_email = "litchi.pi@proton.me"
base_url = "https://litchipi.site"
description = """
  Freelance Rust Software engineer

  Crafting tailor-made software solutions for humans in businesses
"""
copyrights = "Content released under a Creative commons CC BY-NC license"

[plain_context.sources]
og_image = "/static/images/og_banner.png"
content = "https://github.com/litchipi/blog"
engine = "https://github.com/litchipi/ecoweb"

[plain_context.site.social]
github = "https://github.com/litchipi/"
mastodon = "https://fosstodon.org/@litchipi"
email = "mailto:litchi.pi@proton.me"

[plain_context.webring]
name = "Experimental Math & Programming Ring"
previous = "https://scatter.flowers"
next = "https://themathjester.com"

[add_context.banner]
query = "query_context"
args = ["pro", "banner"]


# Storage configuration
[local_storage]
data_root = "./data"
scss_root = "scss"
template_root = "./templates"
supported_lang = [ "fr", "en" ]
include_assets = [
  "images",
  "fonts",
  "scripts",
  "data/static",
]
default_sort = [["date"], false]

[local_storage.scss]
"pro.css" = [
  "pro.scss"
]
"style.css" = [
  "fonts.scss",
  "dark_mode.scss",
  "light_mode.scss",
  "base.scss",
  "banner.scss",
  "nav.scss", 
  "post.scss", 
  "specific.scss", 
  "tablet.scss",
  "phone.scss",
]
"print.css" = [ "print.scss" ]
"poll.css" = [ "poll.scss"]
"code.css" = [ "code.scss" ]
"rss.css" = [ "rss.scss" ]



# Temporary redirections
[redirections]
"/post/11603320942166757384" = "/post/5607614558439774564"
"/post/14762501311625827021" = "/post/17476114125344275704"
"/post/14628100307884912758" = "/post/3630282044331223044"
"/post/17037986568830293248" = "/post/9546819213850085468"
"/post/14221337313176405949" = "/post/392340953423320473"
"/post/17138451467994647381" = "/post/7783911364247322844"




# Mail configuration
[mail]
relay = "in-v3.mailjet.com"
username = "7c6b32b31a794ba0b3b107ea580ab1f3"
password = "212c35e4d70611565dde107b55d3c71d"

from = "Blog <blog@litchipi.site>"
recipient = "LitchiPi <litchi.pi@proton.me>"
pubkey = "MIGJAoGBAK98NWNHYefwkH0ipJ6t6kVcYJmkKX4wf6AwX+HtC9qFLR09wrtqz8q6D3jl/P9sAolXiitdpdSENjLeZgNGY59RLfVh15jdyndgcNzg5OghaMLNLbazeTbKT+mZQYDyBhNi/F1cbGSyeyGJ1KDeo5rnuLcEwZSUh9reRGZNC3aTAgMBAAE="




# Forms configuration

## Contact
[form_endpoints.contact]
endpoint = "/contact"
method = { action = "SendOverEmail", args = "New contact from homepage form" }

[form_endpoints.contact.notification.fr]
title = "Merci"
message = "Merci de votre contact, je vous répondrai dans les meilleurs délais"

[form_endpoints.contact.notification.en]
title = "Thank you"
message = "Thank you for contacting me, be sure I will reply to you very soon"



## Market research
[form_endpoints.market_research]
endpoint = "/save_market_research"
method = { action = "SendOverEmail", args = "New market research answer" }

[form_endpoints.market_research.notification.fr]
title = "Merci"
message = "Merci pour votre contribution !"

[form_endpoints.market_research.notification.en]
title = "Thank you"
message = "Thank you for your contribution !"
