# Index page
[pro_index]
storage = "pro"
route = "/"
lang_detect = true
default_template = "pro_index.html"

[pro_index.add_context.proindex]
query = "query_context"
args = ["pro", "index"]




# Blog index page
[blog_index]
route = "/blog"
lang_detect = true
default_template = "blog_index.html"

[blog_index.add_context.recent_posts]
query = "recent_pages"
args = ["blog", { limit = 5 }]

[blog_index.add_context.all_series]
query = "query_metadata"
args = ["blog", ["serie"]]

[blog_index.add_context.all_categories]
query = "query_metadata"
args = ["blog", ["category"]]




# Blog post
[blog]
route = "/post/{id}"
default_template = "post.html"
content_query = { method = "content_id", args = "id" }

[blog.add_context.same_category]
query = "similar_pages_from_metadata"
args=["blog", ["category"], { limit = 5 }]

[blog.add_context.same_serie]
query = "similar_pages_from_metadata"
args = ["blog", ["serie", "slug"], { sort_by = ["serie", "index"], rev_sort = true }]



# Tag page
[tag]
route = "/tag/{tag_name}"
default_template = "post_list.html"

[tag.add_context.all_posts]
query="similar_pages_from_uri"
args = ["blog", ["tags"], "tag_name", {}]

[tag.add_context.by]
query = "plain"
args = "tag"


# Serie page
[serie]
route = "/serie/{serie_name}"
default_template = "post_list.html"

[serie.add_context.all_posts]
query="similar_pages_from_uri"
args = ["blog", ["serie", "slug"], "serie_name", { sort_by = ["serie", "index"], rev_sort = true }]

[serie.add_context.by]
query = "plain"
args = "serie"



# Category page
[category]
route = "/category/{category_name}"
default_template = "post_list.html"

[category.add_context.all_posts]
query="similar_pages_from_uri"
args = ["blog", ["category"], "category_name", {}]

[category.add_context.by]
query = "plain"
args = "category"



# All posts
[all_posts]
route = "/allposts"
default_template = "post_list.html"

[all_posts.add_context.all_posts]
query = "recent_pages"
args = ["blog", {}]

[all_posts.add_context.by]
query = "plain"
args = "All posts"



# RSS feed
[rss]
route = "/rss"
default_template = "rss_feed.xml"
add_headers = { "Content-Type" = "text/xml;charset=UTF-8"}
minify = false

[rss.add_context.recent_posts]
query = "recent_pages"
args = ["blog", { limit = 0 }]



[humans_txt]
route = "/humans.txt"
default_template = "humans.txt"
add_headers = { "Content-Type" = "text/plain" }
minify = false
