[package]
name = "poll_decode"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
bincode = "1.3.3"
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
rsa = "0.9.6"
serde_json = "1.0.115"
sha2 = "0.10.8"
toml = "0.8.12"
