# TODO  French hireme title
title = "Travaillons ensemble"
introduction = """
  Voici une brève introduction de ce que je fais et *pourquoi* je le fais.  
  Pour parler en détail de toute idée avec vous, je suis à votre entière disposition !

  Envoyez moi un e-mail dès à présent à `litchi.pi@proton.me` !
"""

[why]
title = "Valoriser nos différences"
body = """
  En entreprise, les outils utilisés ont un grand impact sur le *bonheur au travail*.  
  Or le moteur des entreprises à succès, c'est précisément l'ardeur de leurs employés.

  C'est leur ferveur qui permet de **développer** une entreprise au sommet d'une
  économie florissante, et c'est aussi ce qui la **protégera** en cas de crise.
  
  Le **temps humain** est la ressource la plus précieuse d'une entreprise,
  *ne le gaspillons pas* !  
  Recruter des talents est une tâche difficile, il est donc primordial de consacrer
  leur temps judicieusement.  
  Les outils lents, les tâches fastidieuses et les environements de travail inadaptés
  ne vont que *freiner* leur contribution, et saboter l'efficacité de votre entreprise.

  Face au monopole des grands éditeurs de logiciels dans le cyber-espace,
  **ma mission** est de vous apporter de la *sérénité* avec vos outils logiciel,
  proposer *une alternative* aux produits génériques qui pullulent dans l'industrie
  du numérique.

  De par notre diversité, *je crois* qu'un logiciel doit **s'adapter aux personnes**
  qui l'emploient, et non l'inverse.  
  Que vous soyez malvoyant, excentrique, vieillissant, artiste, autiste, geek,
  dyslexique, ou rien de tout cela: nous pouvons *construire ensemble* un logiciel
  qui correspond à votre monde.
"""

[how]
title = "Humaniser la confection de logiciel"
body = """
  Tout commence par **vous**.  
  Ensemble, nous découvrirons ce qui vous empêche de vous sentir à l'aise sur vos outils
  actuels, et nous établirons *votre vision*, votre idéal.

  Nous joindrons nos expertises pour appuyer ce qui est primordial, éliminer ce qui est
  superflu, et modeler cet outil idéal.  
  Notre expertise commune nous permettera de créer une **solution unique**,
  cohérente, épurée, *efficace*.

  Lorsque votre solution idéale sera modelée, alors pourra commencer la confection du
  logiciel, et son ajustement afin qu'il **convienne parfaitement**.  
  Tout au long de ce processus, **vous** serez le maestro, et le logiciel en résultant
  aura été façonné à *votre image*, pour vous apporter de la *sérénité*.
"""

[what]
title = "De meilleurs outils pour une plus grande efficacité"
body = """
  Lors de son utilisation, un outil bien ajusté ne provoquera *aucune tension*,
  et sa manipulation sera naturelle, instinctive.  
  Ma promesse, au délà de cette ergonomie, c'est de concevoir un logiciel
  de *haute qualité*, qui sera **fiable** à travers les années.

  Au coeur de sa conception, le **futur** sera pris en compte afin de faciliter
  toute maintenance ou améliorations qui pourraient être nécessaires.  
  À cet égard, une *documentation complète* sera rédigée, pour aider tout développeur
  à comprendre, maintenir et améliorer ce logiciel.

  *Sécurité*, *maintenabilité*, *performances*, *extensibilité*,
  voici les priorités qui guideront la conception de votre logiciel.  
  Avec ces critères de qualité exigeants, c'est un compagnon **très fiable** que vous
  aurez à vos côtés pour relever tous les défis.
"""

[outro]
title = "Parlez-moi de votre vision"
body = """
  Vous avez un idéal que vous souhaitez partager ?

  Rencontrons-nous, parlons-en en détail, et construisons ensemble votre vision,
  cultivons la sérénité dans votre environnement de travail !

  Contactez-moi dès à présent par e-mail à `litchi.pi@proton.me` !
"""
