title = "Hire me"

introduction = """
  Here is a quick introduction to what I do, and why I do it.  
  If you have something in mind, please feel free to contact me so we can discuss
  it in depth !

  E-mail me today at `litchi.pi@proton.me` !
"""

[why]
title = "Empowering our differences"
body = """
  Tools people use have a big impact on their *happiness at work*,
  and worker's ardour is the engine of every great company.  
  Worker's fervour is what will **drive** a company up a flourishing economy,
  or **protect** it from crashing down in case of a crisis.

  **People's time** is the most expensive resource a company spend, *don't waste it* !  
  Recruiting skilled workers is hard, it's primordial to use their time wisely,
  and *not restrain* their benefit with slow tools, boring manual processes,
  or an un-ergonomic work environment.

  Therefore, against the monopoly of big software companies in the cyberspace,
  **my mission** is to let people *feel free* with their tools,
  enjoy *an alternative* for the crappy software products that cripple
  the digital world.

  Everyone is different, have different ways to think, interact, do,
  and *I believe* that the software should **adapt to the people**,
  not the other way around.  
  Whether you are visually impaired, eccentric, old, artistic, autistic,
  geek, dyslexic, or none of all this;
  there is a software we can *build together* to fit your vision,
  your way, your world.
"""

[how]
title = "Human-first software crafting"
body = """
  Everything starts with **you**, we define precisely together what holds you from
  feeling *easy* with your tools, create the ideal setup, *your vision*.

  Together, we can join our expertises to analyse possible solutions,
  improve what is primordial, remove what is unnecessary,
  and **adapt** the interface to *your liking*, the process to *your methods*.

  After completely *understanding* your ideal, and a solution for it on paper,
  only then will we craft a piece of software, and adjust it so it **fits perfectly**.  
  Until finally you reach a level of *serenity* you deserve to feel with your tools.

  Throughout this process, **you** are the maestro, and the resulting software will be
  to *your image*, not anybody else's.
"""

[what]
title = "Better tools, greater efficiency"
body = """
  A well fitted tool will make you feel *at home*, and relieve the strain 
  from your work using it.  
  Besides this ergonomy, I pledge the software's quality and
  its **reliability** through time.

  While ensuring the **high quality** of the tool created,
  the implementation will also think of the future, when some maintenance or
  improvements will be needed.  
  In this regard, a *complete documentation* will be redacted to enable any software
  engineer to understand, maintain and extend this software.

  *Security*, *maintenability*, *performances*, *extensibility*,
  these are the priorities that will drive the craft of your software.  
  With these high quality standards, you will obtain a very reliable companion
  for your business.
"""

[outro]
title = "Expose me your vision"
body = """
  Have an ideal you wish to share ?
  
  Let's meet, talk about it in depth, and build together your vision,
  cultivate serenity in your work environment !
  
  Contact me today at `litchi.pi@proton.me` !
"""
